
spring.datasource.url=jdbc:mysql://localhost:3306/springsecurityjwt
spring.datasource.username=root
spring.datasource.password=root07

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

app.jwt-secret=376d1cbd98c0ba9babcb26c4d4b784fa7a1b01d40d55d16e28bf4742fa68d28c
app.jwt-expiration=604800000